x-limits: &limits
  deploy:
    resources:
      limits:
        memory: 128m
        cpus: "0.3"
      reservations:
        memory: 64m
        cpus: "0.2"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - model-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5001
      - MODEL_SERVICE_URL=http://model-service:5002
    <<: *limits
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    <<: *limits
    networks:
      - app-network

  cache-service:
    build:
      context: ./cache-service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    <<: *limits
    networks:
      - app-network
      
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - app-network

  log-service:
    build:
      context: ./log-service
      dockerfile: Dockerfile
    ports:
      - "5009:5008"
    volumes:
      - ./log-service/logs:/app/logs
    <<: *limits
    networks:
      - app-network

  model-service:
    build:
      context: ./model-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./model-service/app:/app/app 
    depends_on:
      - cache-service
      - log-service
    #<<: *limits
    networks:
      - app-network

  frontend-service:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    environment:
      - API_GATEWAY_URL=http://api-gateway:5000/service
    <<: *limits
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
