x-limits: &limits
  deploy:
    resources:
      limits:
        memory: 128m
        cpus: "0.3"
      reservations:
        memory: 64m
        cpus: "0.2"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - auth-service
      - model-service
      - log-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5001
      - MODEL_SERVICE_URL=http://model-service:5002
      - TZ=America/Argentina/Buenos_Aires
    <<: *limits
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - TZ=America/Argentina/Buenos_Aires
    <<: *limits
    networks:
      - app-network

  cache-service:
    build:
      context: ./cache-service
      dockerfile: Dockerfile
    depends_on:
      - log-service
    environment:
      - TZ=America/Argentina/Buenos_Aires
    <<: *limits
    networks:
      - app-network
      
  redis:
    image: redis:6.2
    environment:
      - TZ=America/Argentina/Buenos_Aires
    networks:
      - app-network

  log-service:
    build:
      context: ./log-service
      dockerfile: Dockerfile
    volumes:
      - ./log-service/logs:/app/logs
    <<: *limits
    environment:
      - TZ=America/Argentina/Buenos_Aires
    networks:
      - app-network

  model-service:
    build:
      context: ./model-service
      dockerfile: Dockerfile
      args:
        PIP_INSTALL_OPTIONS: "--timeout=120 --retries=3"
    volumes:
      - ./model-service/app:/app/app 
    depends_on:
      - cache-service
      - log-service
    environment:
      - TZ=America/Argentina/Buenos_Aires
    networks:
      - app-network

  frontend-service:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    environment:
      - API_GATEWAY_URL=http://api-gateway:5000/service
      - TZ=America/Argentina/Buenos_Aires
    <<: *limits
    networks:
      - app-network

networks:
  app-network:
    driver: bridge