services:
  mongo:
    image: mongo:latest
    expose:
      - 27017:27017

  predictor:
    image: servidorml:latest
    build: 
      context: ../1_flask
    links:
      - mongo
    expose:
      - 5001:5001

